# Generated by Django 5.0.6 on 2024-05-13 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_code', models.CharField(max_length=50, unique=True, verbose_name='Код ISO валюты')),
                ('name', models.CharField(max_length=250, verbose_name='Название валюты')),
            ],
            options={
                'verbose_name': 'Валюты',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='Currency_exchange_rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата сбора данных')),
                ('value', models.FloatField(verbose_name='Курс валюты')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Курсы валют',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
        migrations.AddConstraint(
            model_name='currency_exchange_rates',
            constraint=models.UniqueConstraint(fields=('currency', 'date'), name='unique_currency_date'),
        ),
    ]
