# Generated by Django 5.0.6 on 2024-05-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Currency_exchange_rates',
            new_name='CurrencyExchangeRates',
        ),
    ]
